default_events:
  - issues
  - pull_request

default_permissions:
  contents: read
  issues: read
  metadata: read
  pull_requests: write



name: Zotera Community Plugin Manager
url: https://zotera.luxass.dev/
description: A GitHub bot for managing Zotera Community Plugins
public: false